defaults:
  - _self_
  - override hydra/hydra_logging: disabled

dataset_dir: ???
labels_dir: ???
output_dir: ???
model_initialization_dir: ???
predictions_fp: ${output_dir}/predictions.parquet
split: "held_out"
demo: false
streaming: true
max_steps: ???
eval_steps: ???
save_steps: 500 # this is the same as the default value in the HuggingFace transformer trainer
seed: 1
num_threads: 4
use_lora: False
lora_rank: 64
finetune_model_type: pooling # options: pooling, lstm

hydra:
  run:
    dir: ${output_dir}
