name: Process Benchmark Result Submissions

on:
  issues:
    types:
      - labeled

jobs:
  process_results:
    if: contains(github.event.issue.labels.*.name, 'result-submission') && startsWith(github.event.issue.title, '[Result Submission]')
    runs-on: ubuntu-latest
    steps:
      - name: Extract JSON from issue body
        id: extract_json
        run: |
          echo '${{ github.event.issue.body }}' > issue_body.txt
          sed -n '/```json/,/```/p' issue_body.txt | sed '1d;$d' > result.json

          if [[ ! -s result.json ]]; then
            echo "ERROR: No valid JSON found in the issue body."
            exit 1
          fi

          echo "Extracted JSON:"
          cat result.json

          echo "RESULT_FILE=result.json" >> $GITHUB_ENV

      - name: Install MEDS-DEV package from PyPI
        run: pip install meds-dev

        #- name: Validate result JSON
        #  run: meds-dev-validate-result results_fp=result.json

      - name: Checkout results branch only
        uses: actions/checkout@v4
        with:
          ref: _results

      - name: Commit result to results branch
        if: success()
        run: |
          mkdir -p _results/${{ github.event.issue.number }}
          mv result.json _results/${{ github.event.issue.number }}/result.json
          git add _results/${{ github.event.issue.number }}/result.json
          git commit -m "Added result from Issue #${{ github.event.issue.number }} in _results branch"
          git push origin _results

      - name: Close issue with confirmation message
        if: success()
        uses: peter-evans/close-issue@v2
        with:
          comment: "Thank you for your submission! Your result has been recorded and validated."
