name: Process Benchmark Result Submissions

on:
  issues:
    types:
      - labeled

jobs:
  process_results:
    if: contains(github.event.issue.labels.*.name, 'result-submission') && startsWith(github.event.issue.title, '[Result Submission]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout results branch only
        uses: actions/checkout@v4
        with:
          ref: _results
          sparse-checkout: true
          sparse-checkout-cone-mode: false
          path: _results

      - name: Install jq for JSON parsing
        run: sudo apt-get install jq -y

      - name: Check for attached JSON file
        id: check_attachment
        run: |
          ATTACHMENT_URL=$(echo '${{ toJson(github.event.issue) }}' | jq -r '.issue.body' | grep -o 'https://github.com/[^ ]*\.json' || echo "")
          if [[ -z "$ATTACHMENT_URL" ]]; then
            echo "ERROR: No attached JSON file found in the issue. Submission must include a JSON attachment."
            exit 1
          fi
          echo "Detected attached JSON file: $ATTACHMENT_URL"
          curl -L "$ATTACHMENT_URL" -o result.json
          echo "RESULT_FILE=result.json" >> $GITHUB_ENV

      - name: Install MEDS-DEV package from PyPI
        run: pip install meds-dev

      - name: Validate result JSON
        run: meds-dev-validate-result results_fp=result.json

      - name: Commit result to results branch
        if: success()
        run: |
          mkdir -p _results/${{ github.event.issue.number }}
          mv result.json _results/${{ github.event.issue.number }}/result.json
          git add _results/${{ github.event.issue.number }}/result.json
          git commit -m "Added result from Issue #${{ github.event.issue.number }} in _results branch"
          git push origin _results

      - name: Close issue with confirmation message
        if: success()
        uses: peter-evans/close-issue@v2
        with:
          comment: "Thank you for your submission! Your result has been recorded and validated."
